application:
  name: brasserie-76-flo
  project: brasserie-76-flo
  port: 8000
  publicly_accessible: true
databases:
  - type: postgresql
    name: bakpakerdb
    version: "12.6.0"
routers:
  - name: main
    routes:
      - application_name: brasserie-76-flo
        paths:
          - /
