application:
  name: brasserie-bakpaker-qovery
  project: brasserie-bakpaker-qovery
  port: 8000
  publicly_accessible: true
databases:
  - type: postgresql
    name: bakpakdb
    version: "12.6.0"
routers:
  - name: main
    routes:
      - application_name: brasserie-bakpaker-qovery
        paths:
          - /
