# Generated by Django 3.1.3 on 2021-05-29 20:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatesMapDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_coordinates', models.CharField(max_length=500)),
                ('name_of_locations', models.CharField(max_length=300)),
                ('adresse', models.CharField(max_length=300)),
                ('code_postal', models.CharField(max_length=300)),
                ('localite', models.CharField(max_length=300)),
                ('categories', models.CharField(choices=[('Brasserie', 'Brasserie Bakpaker'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Marche', 'Marché')], default='Brasserie', max_length=300)),
                ('informations_supplementaires', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@gmail.com', max_length=254)),
            ],
        ),
    ]
