# Generated by Django 3.1.3 on 2021-06-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakpak_website', '0003_coordinatesmapdb_url_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatesmapdb',
            name='url_coordinates',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
