# Generated by Django 3.1.3 on 2021-06-08 17:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bakpak_website', '0004_auto_20210604_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatesmapdb',
            name='categories',
            field=models.CharField(choices=[('Brasserie', 'Brasserie Bakpaker'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Marche', 'Marché')], default='Brasserie', help_text='Chaque catégorie renvoie à un logo différent sur la carte.', max_length=300),
        ),
        migrations.AlterField(
            model_name='coordinatesmapdb',
            name='informations_supplementaires',
            field=tinymce.models.HTMLField(help_text="Ici tu peux mettres les horaires d'ouvertures, les prix de ventes etc..."),
        ),
        migrations.AlterField(
            model_name='coordinatesmapdb',
            name='url_coordinates',
            field=models.CharField(default='N/A', help_text="Copiez-collez une url de google maps, le plus important c'est ce qu'il y aprés !3d et !4d.", max_length=500),
        ),
    ]
